# Generated by Django 5.1.6 on 2025-04-04 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BikeBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='BikePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField(help_text='Cena v Kč')),
                ('bike', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='price', to='bikes.bikebrand')),
            ],
        ),
        migrations.CreateModel(
            name='BikeSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frame', models.CharField(max_length=100)),
                ('fork', models.CharField(max_length=100)),
                ('shock', models.CharField(max_length=100)),
                ('brakes', models.CharField(max_length=100)),
                ('tires', models.CharField(max_length=100)),
                ('derailleur', models.CharField(max_length=100)),
                ('weight', models.FloatField(help_text='Váha v kg')),
                ('bike', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='specs', to='bikes.bikebrand')),
            ],
        ),
    ]
